# Generated by Django 4.2.28 on 2026-02-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('author_name_cache', models.CharField(blank=True, help_text='Cached author name (preserved if account is deleted)', max_length=100)),
                ('guest_name', models.CharField(blank=True, help_text='Name for non-logged-in users', max_length=100)),
                ('guest_email', models.EmailField(blank=True, help_text='Email for notifications (not displayed publicly)', max_length=254)),
                ('content', models.TextField(help_text='Comment text content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Requires approval for guest comments')),
                ('is_edited', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin important comments')),
            ],
            options={
                'ordering': ['-is_pinned', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_content', models.TextField(help_text='Content before edit')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Comment edit histories',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name_cache', models.CharField(blank=True, help_text='Cached sender name (preserved if account is deleted)', max_length=100)),
                ('notification_type', models.CharField(choices=[('comment_reply', 'Comment Reply'), ('comment_like', 'Comment Like'), ('comment_mention', 'Mentioned in Comment'), ('post_comment', 'New Comment on Your Post')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comments.comment')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
