# Generated by Django 4.2.28 on 2026-02-11 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_commentedithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name_cache',
            field=models.CharField(blank=True, help_text='Cached author name (preserved if account is deleted)', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_name_cache',
            field=models.CharField(blank=True, help_text='Cached sender name (preserved if account is deleted)', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Registered user who made the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='User who triggered the notification (null for guest users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
