# Generated by Django 4.1.13 on 2026-01-27 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails_otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsotprecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
