# Generated by Django 4.2.28 on 2026-02-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_notification_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdPlacement',
        ),
    ]
