# Generated by Django 4.2.28 on 2026-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_commentlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Order within category (lower = first)'),
        ),
    ]
